[project]
authors = ["Mira AMM"]
entry = "main.sw"
license = "Apache-2.0"
name = "asset_wrapper_contract"

[dependencies]
interfaces = { path = "../../libraries/interfaces" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.2" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.23.1" }
